# Generated by Django 4.2.7 on 2024-03-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="relevant_posts",
        ),
        migrations.CreateModel(
            name="RelevantPosts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=31)),
                ("history", models.ManyToManyField(related_name="profiles", to="main.post")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
