# Generated by Django 4.2.7 on 2024-03-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_initial"),
        ("users", "0002_remove_profile_relevant_posts_relevantposts"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryWatchers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.profile")),
                ("story", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.post")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
