# Generated by Django 4.2.7 on 2024-03-07 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_storywatchers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storywatchers",
            name="count",
        ),
    ]
