# Generated by Django 4.2.7 on 2024-03-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_storywatchers_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storywatchers",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="storywatchers",
            name="story",
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile/images/"),
        ),
        migrations.DeleteModel(
            name="ProfileImage",
        ),
        migrations.DeleteModel(
            name="StoryWatchers",
        ),
    ]
