# Generated by Django 4.2.7 on 2024-03-09 13:47

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_storywatchers_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to="profile/images/"),
        ),
    ]
