# Generated by Django 4.2.7 on 2024-03-09 13:58

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="profile/images/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="image3_thumbnail",
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to="profile/images/"),
            preserve_default=False,
        ),
    ]
